README.md
=> Attempted to fix issue #1

galaxy-chop.py, utils/aling.py, utils/dens.py, utils/equal_number.py
I took out the core and passed the functions to utils
=> issues#8 fixed

galaxy-chop/aling.py, galaxy-chop/density.py, galaxy-chop/equal_number.py, galaxy-chop/galaxy-chop.py, resource/potential.f90, resource/potential_TNG.f90
I create two folders, one with the source code named 'galaxy-chop' and other folder with resource code, containing Fortran files named resource.
=> Attempt to fix issue#7

README.md
Nelson, please check your name and add your email.
=> add_authors_issue#9

galaxy-chop/galaxy-chop.py, galaxy-chop/utils.py
On galaxy-chop.py only left this issue galaxy-chop.py:8:3: E999 SyntaxError: invalid syntax - solves issues #26
=> I run flake8 on the files galaxy-chop.py and utils.py - solves issues #26

galaxy-chop/galaxy-chop.py
I added the outline of the structure of the main classes - solves issues #27
=> I added the structure with the main API classes - solves issues #27

galaxychop/galaxychop.py
=> I removed the API user interface design from the core module 

galaxychop/utils.py
I wrote the documentation (the parameters and returns) of the _get_rot_matrix and aling functions of utils.py - solves issues #37
=> I wrote the documentation of the _get_rot_matrix and aling functions of utils.py 

tox.ini
=> tox.ini_issues#30

galaxychop/galaxychop.py
This is one of the two main classes of the API. This class will calculate the dynamic quantities needed for dynamic decomposition. - issue #39 .
=> I started to create the galaxy class

.gitignore, README.md, galaxychop/galaxychop.py, galaxychop/utils.py, tests/test_input.py
Here I have modified the README.md file, adding documentation and Travis badget.
Besides I have made the tests for rotation programs. I have to mention that the tests passed, but on several occasions fail, I think that it is because some random number that is not taking the seed. But it's just a matter of readjusting the tolerance or running the test again.
=> Issue35 Documentation added and rotational tests

LICENSE.txt, galaxychop/galaxychop.py, galaxychop/utils.py, tests/test_methods.py
I finally removed the "if" statement from the code. I also corrected some style errors in other files. Please check that this is all right.
=> I removed the if statement from the code - fixes issue #43

galaxychop/galaxychop.py, galaxychop/utils.py, legacy/units_test.ipynb, setup.py, tox.ini
This issue fixes units validation with astropy units
It is not finished yet, It is a draft version
=> units validaton

galaxychop/utils.py
Now the function rotates all the particles with only one rotation matrix.
=> modification of the aling function to correct the way it works

galaxychop/galaxychop.py, galaxychop/utils.py, tests/test_input.py
This branch has some minor changes that we were talking about...
=> Minor changes

galaxychop/core.py
Add some of the documentation maybe there are things missing
=> Added some documentation

galaxychop/models.py, tests/test_models.py
I made a modification to the decompose method, to make the implementation of the scikit-learn wrappers easier.
=> modification of method decompose and decomposition method tests

galaxychop/models.py, tests/test_models.py
New GCChop class that implements the dynamic decomposition method that uses a cutoff value in circularity parameter.
=> New GCChop class with tests.

galaxychop/models.py, tests/test_models.py
I added the class with the last decomposer and its tests.
=> I added the GCJE class in models.py

README.md, docs/source/api/galaxychop.rst, docs/source/tutorial.ipynb
I add the motivation into the readme
change three for six methods 
and modificate the API introduction
=> minor changes in the documentation in general 
